name: C# CI

on:
  push:
    paths-ignore:
      - '*.md'
      - 'LICENSE*'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE*'
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Monthly

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: microsoft/setup-msbuild@v1.0.2
    - name: Build
      run: msbuild /m /nologo /t:Build /p:Configuration=Release Decompiler.sln
    - name: Prepare artifacts
      run: rm Decompiler/bin/Release/* -Include *.config, *.pdb
    - uses: actions/upload-artifact@v2
      with:
        name: bsp-decompiler
        path: Decompiler/bin/Release
